# Generated by Django 3.1.6 on 2021-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResCode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد')),
                ('desc', models.CharField(max_length=255, verbose_name='شرح کد')),
            ],
        ),
    ]
