# Generated by Django 3.1.6 on 2021-02-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_paymentrescode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrescode',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='وضعیت'),
        ),
    ]
