# Generated by Django 3.1.6 on 2021-02-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_paymentrescode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان استان')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان شهر')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_city', to='Api.city', verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایشی')),
                ('national_code', models.CharField(max_length=11, verbose_name='کد ملی')),
                ('password', models.CharField(max_length=255, verbose_name='کلمه عبور')),
                ('phone1', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('phone2', models.CharField(max_length=11, verbose_name='تلفن همراه دوم')),
                ('first_name', models.CharField(max_length=40, verbose_name='نام')),
                ('last_name', models.CharField(max_length=40, verbose_name='نام خانوادگی')),
                ('grade', models.IntegerField(choices=[(10, 'دهم'), (11, 'یازدهم')], verbose_name='پایه تحصیلی')),
                ('status', models.IntegerField(default=0, verbose_name='وضعیت')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_city', to='Api.city', verbose_name='شهر')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school', to='Api.school', verbose_name='مدرسه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_province', to='Api.province', verbose_name='استان'),
        ),
    ]
