# Generated by Django 3.1.6 on 2021-02-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210206_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='pay_student', to='Api.student', verbose_name='دانش آموز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_city', to='Api.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(10, 'دهم'), (11, 'یازدهم')], null=True, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه دوم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_school', to='Api.school', verbose_name='مدرسه'),
        ),
    ]
