# Generated by Django 3.1.6 on 2021-02-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20210212_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='return_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک بازگشت'),
        ),
    ]
