# Generated by Django 3.1.6 on 2021-02-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20210213_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات خام بازگشتی'),
        ),
    ]
