# Generated by Django 3.1.6 on 2021-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_payment_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مدرسه'),
        ),
    ]
