# Generated by Django 3.1.6 on 2021-02-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_auto_20210225_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='عنوان سوال'),
        ),
    ]
