# Generated by Django 3.1.6 on 2021-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه'),
        ),
    ]
