# Generated by Django 3.1.6 on 2021-02-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_exam_ending_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='question',
        ),
    ]
