# Generated by Django 3.1.7 on 2021-03-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_auto_20210225_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAN', 'مرد'), ('WOMAN', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'متن'), (2, 'فیلم'), (3, 'عکس'), (4, 'بازی'), (5, 'پاسخ')], default=1, verbose_name='نوع محتوا'),
        ),
    ]
