# Generated by Django 3.0.4 on 2021-03-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_answer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='نظر مصحح'),
        ),
    ]
