# Generated by Django 3.0.4 on 2021-04-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_auto_20210404_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudent',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='نمره'),
        ),
    ]
