# Generated by Django 3.0.4 on 2021-04-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0026_examstudent_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examstudent',
            name='can_register',
        ),
        migrations.RemoveField(
            model_name='examstudent',
            name='is_pass',
        ),
        migrations.RemoveField(
            model_name='examstudent',
            name='is_preregister',
        ),
        migrations.RemoveField(
            model_name='examstudent',
            name='is_register_complete',
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
