# Generated by Django 3.0.4 on 2021-04-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_auto_20210414_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_exam', to='Api.Exam', verbose_name='پیش\u200cنیاز'),
        ),
    ]
