# Generated by Django 3.0.4 on 2021-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0029_auto_20210417_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='examstudent',
            name='status',
            field=models.IntegerField(choices=[(0, 'مجاز به ثبت\u200cنام'), (1, 'ثبت\u200cنام کرده'), (2, 'پذیرفته\u200cشده'), (3, 'پذیرفته\u200cنشده')], default=0, verbose_name='وضعیت دانش\u200cآموز نسبت به آزمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='required_score',
            field=models.IntegerField(default=0, verbose_name='کف نمره\u200cی قبولی'),
        ),
    ]
