# Generated by Django 3.0.4 on 2021-04-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0030_auto_20210417_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ثبت\u200cنام (ریال)'),
        ),
    ]
