# Generated by Django 3.0.4 on 2021-04-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0031_auto_20210418_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='required_score',
            field=models.IntegerField(default=0, verbose_name='نمره\u200cی قبولی'),
        ),
    ]
