# Generated by Django 3.0.4 on 2021-04-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0032_auto_20210419_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='registration_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات ثبت\u200cنام'),
        ),
    ]
