# Generated by Django 3.0.4 on 2021-04-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0033_exam_registration_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstudent',
            name='status',
            field=models.IntegerField(choices=[(0, 'مجاز به ثبت\u200cنام'), (1, 'ثبت\u200cنام شده'), (2, 'پذیرفته\u200cشده'), (3, 'پذیرفته\u200cنشده')], default=0, verbose_name='وضعیت دانش\u200cآموز نسبت به آزمون'),
        ),
    ]
