# Generated by Django 3.0.4 on 2021-05-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0035_exam_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='نمره\u200cی سوال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='نظر مصححین'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='نمره\u200cی تصحیح اول'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='هزینه\u200cی ثبت\u200cنام (ریال)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_exam', to='Api.Exam', verbose_name='آزمونِ پیش\u200cنیاز'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='examstudent',
            name='status',
            field=models.IntegerField(choices=[(0, 'مجاز به ثبت\u200cنام'), (1, 'ثبت\u200cنام شده'), (2, 'پذیرفته\u200cشده'), (3, 'پذیرفته\u200cنشده')], default=0, verbose_name='وضعیت دانش\u200cآموز'),
        ),
    ]
