# Generated by Django 3.0.4 on 2021-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0036_auto_20210515_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='final_score',
            field=models.IntegerField(default=0, verbose_name='نمره\u200cی نهایی'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correction_ok',
            field=models.BooleanField(default=False, verbose_name='آیا تصحیح نهایی شده است یا نه؟'),
        ),
        migrations.AddField(
            model_name='answer',
            name='score2',
            field=models.IntegerField(default=0, verbose_name='نمره\u200cی تصحیح دوم'),
        ),
    ]
