# Generated by Django 3.0.4 on 2021-05-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0037_auto_20210515_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='score',
            new_name='score1',
        ),
    ]
