# Generated by Django 3.2.3 on 2021-08-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0038_auto_20210515_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا رویداد عمومی است یا نه؟'),
        ),
    ]
