# Generated by Django 3.0.4 on 2021-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0039_auto_20210519_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correction_ok',
            field=models.BooleanField(default=False, verbose_name='آیا تصحیح نهایی شده است؟'),
        ),
    ]
