# Generated by Django 3.2.3 on 2021-06-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0040_auto_20210601_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
