# Generated by Django 3.2.3 on 2021-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0041_payment_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ایمیل'),
        ),
    ]
