# Generated by Django 3.2.3 on 2021-08-17 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Game', '0002_alter_playerproblem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='قیمت')),
                ('problem_for_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.playersingleproblem', verbose_name='سوال برای فروش')),
            ],
        ),
    ]
