# Generated by Django 3.2.3 on 2021-08-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_alter_playerproblem_status'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='problem_for_sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.playersingleproblem', verbose_name='سوال برای فروش'),
        ),
    ]
