# Generated by Django 3.2.3 on 2021-08-17 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_alter_playerproblem_status'),
        ('auction', '0002_alter_auction_problem_for_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='problem_for_sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.problem', verbose_name='سوال برای فروش'),
        ),
    ]
