# Generated by Django 3.0.4 on 2021-04-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formula0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایشی')),
                ('mode', models.CharField(choices=[], max_length=40, verbose_name='حالت')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایشی')),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='نام و نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.CreateModel(
            name='ProblemTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایشی')),
                ('score', models.IntegerField(default=0, verbose_name='نمره')),
                ('status', models.IntegerField(choices=[], default=0, verbose_name='وضعیت')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Formula0.Problem', verbose_name='مسئله')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Formula0.Team', verbose_name='تیم')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
