# Generated by Django 3.0.4 on 2021-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula0', '0003_auto_20210404_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResCode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد')),
                ('desc', models.CharField(max_length=255, verbose_name='شرح کد')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='وضعیت')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='grade',
            field=models.CharField(choices=[(6, 'ششم'), (7, 'هفتم'), (8, 'هشتم'), (9, 'نهم'), (10, 'دهم'), (11, 'یازدهم'), (12, 'دوازدهم')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
    ]
