# Generated by Django 3.0.4 on 2021-04-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula0', '0008_auto_20210404_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentResCode',
        ),
        migrations.AlterField(
            model_name='problemteam',
            name='status',
            field=models.IntegerField(choices=[(0, 'گرفته نشده'), (1, 'گرفته شده'), (2, 'در حال تصحیح'), (3, 'صحیح شده'), (4, 'به مزایده گذاشته شده'), (5, 'در مزایده واگذار شده')], default=0, verbose_name='وضعیت'),
        ),
    ]
