# Generated by Django 3.0.4 on 2021-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula0', '0010_auto_20210405_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='نام'),
        ),
    ]
