# Generated by Django 3.0.4 on 2021-04-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula0', '0011_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemteam',
            name='auction_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه در مزایده'),
        ),
        migrations.AlterField(
            model_name='problemteam',
            name='status',
            field=models.IntegerField(choices=[(0, 'گرفته نشده'), (1, 'گرفته شده'), (2, 'در حال تصحیح'), (3, 'صحیح شده'), (4, 'به مزایده گذاشته شده'), (5, 'در مزایده واگذار شده')], default=1, verbose_name='وضعیت'),
        ),
    ]
